### ISSUE TITLE
Use SBT version from `project/build.properties` if available

### ISSUE THREAD

**Issue by carlosedp** [Jtalk/setup-sbt#1]
It would be nice if the action could use the SBT version specified in `project/build.properties` if available.

It could override the version specified in the action setup or make that optional.

**Comment by carlosedp** [comment]
As a workaround, I added a task before the setup-sbt action that fetches my project version:

```yaml
    - name: Get project SBT version
      run: echo "SBT_VERSION=$(cat project/build.properties |cut -d= -f2)" >> $GITHUB_ENV
      id: sbt-version

    - name: Install SBT
      uses: Jtalk/setup-sbt@v1
      with:
        version: ${{ env.SBT_VERSION }}
```
